// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EgaWbo7FJ6FVrzYgS2dt7jC2TaDwuvg',
    appId: '1:245217712334:web:1d868fee9021f060b2189f',
    messagingSenderId: '245217712334',
    projectId: 'alarmaantiolvidos',
    authDomain: 'alarmaantiolvidos.firebaseapp.com',
    storageBucket: 'alarmaantiolvidos.firebasestorage.app',
    measurementId: 'G-838E8QGSN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHY-Pfic4ihEFDmqpHDhQuVZjR9XQlUI',
    appId: '1:245217712334:android:d0fe128e00a3ad2bb2189f',
    messagingSenderId: '245217712334',
    projectId: 'alarmaantiolvidos',
    storageBucket: 'alarmaantiolvidos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjN-VCUDOCq8_b6O4eU2Q10TFGD9pCC-k',
    appId: '1:245217712334:ios:e28e429d7909a53ab2189f',
    messagingSenderId: '245217712334',
    projectId: 'alarmaantiolvidos',
    storageBucket: 'alarmaantiolvidos.firebasestorage.app',
    iosBundleId: 'com.esail.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjN-VCUDOCq8_b6O4eU2Q10TFGD9pCC-k',
    appId: '1:245217712334:ios:e28e429d7909a53ab2189f',
    messagingSenderId: '245217712334',
    projectId: 'alarmaantiolvidos',
    storageBucket: 'alarmaantiolvidos.firebasestorage.app',
    iosBundleId: 'com.esail.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EgaWbo7FJ6FVrzYgS2dt7jC2TaDwuvg',
    appId: '1:245217712334:web:dfce66b4c7f7d201b2189f',
    messagingSenderId: '245217712334',
    projectId: 'alarmaantiolvidos',
    authDomain: 'alarmaantiolvidos.firebaseapp.com',
    storageBucket: 'alarmaantiolvidos.firebasestorage.app',
    measurementId: 'G-PSG0NDD616',
  );

}