spring.application.name=Alarma Anti Olvidos
# Conexi�n a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=sql_server_local;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
spring.datasource.username=sa
spring.datasource.password=A1B2C3D4%
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuraci�n de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
trustServerCertificate=true

# Ruta al archivo de Firebase (puedes cambiarla seg�n el entorno)
firebase.config.path=classpath:firebase-service-account.json